#! /usr/bin/env python
import sys
from os.path import splitext
from antlr4.FileStream import FileStream
from antlr4.CommonTokenStream import CommonTokenStream
from ukeleleLexer import ukeleleLexer
from ukeleleParser import ukeleleParser
from symbolsTable import SymbolsTable

def main():
    char_stream = FileStream(sys.argv[1])
    lexer = ukeleleLexer(char_stream)
    tokens = CommonTokenStream(lexer)
    parser = ukeleleParser(tokens);

    initial_ts = SymbolsTable()
    code = parser.s(initial_ts)

    filename, fileextesion = splitext(sys.argv[1])

    with open(filename + '.ukil', 'w') as out:
        out.write(code.code)

if __name__ == '__main__':
    main()
